// pages/index.vue
<template>
    <div class="index">
        <ul>
            <li><NuxtLink to="/blog">blog<img id="arrow" src="~/assets/img/symbols/next.svg"/></NuxtLink></li>
            <li><NuxtLink to="/projects">projects<img id="arrow" src="~/assets/img/symbols/next.svg"/></NuxtLink></li>

            <br/>

            <li><a target="_blank" href="mailto:contact@kevinle.com.au">email<img id="arrow" src="~/assets/img/symbols/new.svg"/></a></li>
            <li><a target="_blank" href="https://twitter.com/kevinle_1">twitter<img id="arrow" src="~/assets/img/symbols/new.svg"/></a></li>
            <li><a target="_blank" href="https://github.com/kevinle-1">github<img id="arrow" src="~/assets/img/symbols/new.svg"/></a></li>
            <li><a target="_blank" href="https://www.linkedin.com/in/kevinle14">linkedin<img id="arrow" src="~/assets/img/symbols/new.svg"/></a></li>

            <br/>
            <li><a target="_blank" href="/files/kevin-le-resume-pub2021.pdf">résumé<img id="arrow" src="~/assets/img/symbols/new.svg"/></a></li>

            <br/>

            <li><img id="switch" src="~/assets/img/symbols/bulb.svg"/></li>
        </ul>
    </div>
</template>

<script>
import $ from 'jquery'

export default {
  mounted () {
    $('.top #brand #subheading').attr('src', '')
    $('.top #brand').removeClass('active')

    $('#switch').click(function () {
      $('.content').toggleClass('stealth')
      $('body').toggleClass('stealth')
    })
  }
}
</script>

// pages/index.tsx
import type { NextPage } from 'next'
import styles from '../styles/Home.module.scss'

import Header from '../components/k/Header'
import Sidebar from '../components/k/Sidebar'

import Chevron from '../assets/img/chevron.svg'
import Link from 'next/link'

import PageHead from './_head'

interface Links {
  name: string,
  url: string,
  nextLink?: boolean
}

const Home: NextPage = () => {
  const links: Links[] = [{
    name: "Email",
    url: "mailto:hi@kevle.xyz"
  },
  {
    name: "GitHub",
    url: "https://github.com/kevinle-1"
  },
  {
    name: "LinkedIn",
    url: "https://www.linkedin.com/in/kevinle14/"
  },
  // {
  //   name: "Resume",
  //   url: "/"
  // },
  {
    name: "Blog",
    url: "/blog",
    nextLink: true
  }];

  return (
    <div className={styles.container}>
      <PageHead description="Software Engineer"/>

      <Header title="Software Engineer"/>
      <Sidebar sidebarOnly={true} mobileShowIcons={true}/>
      <div className="links">
        { links.map(l =>
          l.nextLink == null || l.nextLink == false ?
          <span><a href={l.url} target="_blank">{l.name}</a></span> :
          <span><Link href={l.url}>{l.name}</Link></span>
        )}
      </div>

      <div className="chevron">
        <Chevron/>
      </div>
    </div>
  )
}

export default Home
